name: openSSH

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install OpenSSH
        run: sudo apt-get update && sudo apt-get install -y openssh-server

      - name: Install ZeroTier
        run: |
          curl -s https://install.zerotier.com | sudo bash

      - name: lay root
        run: |
           sudo su

      - name: join
        run: |
          zerotier-cli join ebe7fbd445980765

      - name: ZeroTier
        run: |
          zerotier-one

      - name: loop
        run: |
         while true; do
         ping -c 1 127.0.0.1
          done
          
      
